package oriedita.editor.swing.component;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import oriedita.editor.AnimationDurations;
import oriedita.editor.Animations;
import oriedita.editor.databinding.FoldedFigureModel;
import oriedita.editor.databinding.MeasuresModel;
import oriedita.editor.factory.RegexHighlightFactory;
import oriedita.editor.service.AnimationService;
import oriedita.editor.service.ButtonService;
import oriedita.editor.swing.InputEnterKeyAdapter;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;

public class FoldedFigureResize extends JPanel {
    private final ButtonService buttonService;
    private final FoldedFigureModel foldedFigureModel;
    private final MeasuresModel measuresModel;
    private final AnimationService animationService;
    private JButton foldedFigureSizeDecreaseButton;
    private JPanel panel1;
    private JTextField foldedFigureSizeTextField;
    private JButton foldedFigureSizeSetButton;
    private JButton foldedFigureSizeIncreaseButton;

    public FoldedFigureResize(ButtonService buttonService,
                              FoldedFigureModel foldedFigureModel,
                              MeasuresModel measuresModel,
                              AnimationService animationService) {
        this.buttonService = buttonService;
        this.foldedFigureModel = foldedFigureModel;
        this.measuresModel = measuresModel;
        this.animationService = animationService;
        add($$$getRootComponent$$$());
    }

    public void init() {
        buttonService.registerButton(foldedFigureSizeSetButton, "foldedFigureSizeSetAction");
        buttonService.registerButton(foldedFigureSizeDecreaseButton, "foldedFigureSizeDecreaseAction");
        buttonService.registerButton(foldedFigureSizeIncreaseButton, "foldedFigureSizeIncreaseAction");

        foldedFigureSizeSetButton.addActionListener(e ->
                animationService.animate(Animations.ZOOM_FOLDED_MODEL, foldedFigureModel::setScale, foldedFigureModel::getScale,
                        s -> measuresModel.string2double(foldedFigureSizeTextField.getText(), foldedFigureModel.getScale()), AnimationDurations.ZOOM)
        );
        foldedFigureSizeTextField.addActionListener(e -> foldedFigureSizeSetButton.doClick());
        foldedFigureSizeTextField.getDocument().addDocumentListener(RegexHighlightFactory.doubleRegexAdapter(foldedFigureSizeTextField));
        foldedFigureSizeTextField.addKeyListener(new InputEnterKeyAdapter(foldedFigureSizeTextField));
        foldedFigureSizeTextField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                animationService.animate(Animations.ZOOM_FOLDED_MODEL, foldedFigureModel::setScale, foldedFigureModel::getScale,
                        s -> measuresModel.string2double(foldedFigureSizeTextField.getText(), foldedFigureModel.getScale()), AnimationDurations.ZOOM);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
        foldedFigureSizeDecreaseButton = new JButton();
        foldedFigureSizeDecreaseButton.setIcon(new ImageIcon(getClass().getResource("/ppp/oriagari_syukusyou.png")));
        panel1.add(foldedFigureSizeDecreaseButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        foldedFigureSizeTextField = new JTextField();
        foldedFigureSizeTextField.setColumns(2);
        foldedFigureSizeTextField.setHorizontalAlignment(4);
        panel1.add(foldedFigureSizeTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(30, -1), null, null, 0, false));
        foldedFigureSizeSetButton = new JButton();
        foldedFigureSizeSetButton.setText("S");
        panel1.add(foldedFigureSizeSetButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        foldedFigureSizeIncreaseButton = new JButton();
        foldedFigureSizeIncreaseButton.setIcon(new ImageIcon(getClass().getResource("/ppp/oriagari_kakudai.png")));
        panel1.add(foldedFigureSizeIncreaseButton, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    public String getText() {
        return foldedFigureSizeTextField.getText();
    }

    public void setText(String text) {
        foldedFigureSizeTextField.setText(text);
        foldedFigureSizeTextField.setCaretPosition(0);
    }
}
