package oriedita.editor.swing;


import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.tinylog.Logger;
import oriedita.editor.Canvas;
import oriedita.editor.CanvasUI;

import javax.swing.JComponent;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.concurrent.Executor;

/**
 * BorderLayout for each different part.
 */
@ApplicationScoped
public class Editor {
    private final Canvas canvas1;
    private JPanel root;
    private CanvasUI canvas;
    private ToolsPanel toolsPanel;
    private TopToolbar topToolbar;

    @Inject
    public Editor(Canvas canvas, ToolsPanel toolsPanel, TopToolbar topToolbar) {
        this.canvas1 = canvas;
        this.toolsPanel = toolsPanel;
        this.topToolbar = topToolbar;

        $$$setupUI$$$();
    }

    public void init(Executor service) throws InterruptedException {
        service.execute(toolsPanel::init);
        service.execute(topToolbar::init);
    }

    private void createUIComponents() {
        this.canvas = canvas1.getCanvasImpl();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        root = new JPanel();
        root.setLayout(new BorderLayout(0, 0));
        root.add(toolsPanel.$$$getRootComponent$$$(), BorderLayout.WEST);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        root.add(panel1, BorderLayout.CENTER);
        panel1.add(topToolbar.$$$getRootComponent$$$(), BorderLayout.NORTH);
        panel1.add(canvas, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

    public ToolsPanel getToolsPanel() {
        return toolsPanel;
    }

    public TopToolbar getTopToolbar() {
        return topToolbar;
    }

}
