package oriedita.editor.swing;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import oriedita.common.converter.DoubleConverter;
import oriedita.editor.Colors;
import oriedita.editor.databinding.ApplicationModel;
import oriedita.editor.databinding.CameraModel;
import oriedita.editor.databinding.CanvasModel;
import oriedita.editor.databinding.GridModel;
import oriedita.editor.service.ButtonService;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;

@ApplicationScoped
public class TopToolbar {
    private JPanel root;
    private JButton cycleGridButton;
    private JButton decreaseGridSizeButton;
    private JTextField gridSizeTextField;
    private JButton increaseGridSizeButton;
    private JButton resetButton;
    private JButton foldButton;
    private JButton stopFoldingButton;
    private JButton trashButton;
    private JButton mountainButton;
    private JButton valleyButton;
    private JButton edgeButton;
    private JButton auxButton;
    private JButton moveButton;
    private JButton zoomInButton;
    private JButton zoomOutButton;
    private JTextField zoomTextField;
    private JButton rotateCounterClockwiseButton;
    private JButton rotateClockwiseButton;
    private JTextField rotationTextField;
    private JCheckBox foldabilityCheckbox;

    private final ButtonService buttonService;
    private final GridModel gridModel;
    private final CanvasModel canvasModel;
    private final CameraModel creasePatternCameraModel;
    private final ApplicationModel applicationModel;

    @Inject
    public TopToolbar(ButtonService buttonService,
                      GridModel gridModel,
                      CanvasModel canvasModel,
                      CameraModel creasePatternCameraModel,
                      ApplicationModel applicationModel) {
        this.buttonService = buttonService;
        this.gridModel = gridModel;
        this.canvasModel = canvasModel;
        this.creasePatternCameraModel = creasePatternCameraModel;
        this.applicationModel = applicationModel;
    }

    public void init() {
        buttonService.addDefaultListener($$$getRootComponent$$$());

        canvasModel.addPropertyChangeListener(e -> setData(canvasModel));
        applicationModel.addPropertyChangeListener(e -> setData(applicationModel));

        gridModel.bind(gridSizeTextField, "gridSize");
        creasePatternCameraModel.bind(zoomTextField, "scale", new DoubleConverter("0.0####"));
        creasePatternCameraModel.bind(rotationTextField, "rotation", new DoubleConverter("0.0####"));
    }

    private void setData(ApplicationModel applicationModel) {
        foldabilityCheckbox.setSelected(applicationModel.getCheck4Enabled());
    }

    private void setData(CanvasModel data) {
        Color gray = Colors.get(new Color(150, 150, 150));

        edgeButton.setBackground(gray);
        edgeButton.setForeground(Colors.get(Color.black));
        mountainButton.setBackground(gray);
        mountainButton.setForeground(Colors.get(Color.black));
        valleyButton.setBackground(gray);
        valleyButton.setForeground(Colors.get(Color.black));
        auxButton.setBackground(gray);
        auxButton.setForeground(Colors.get(Color.black));

        switch (data.calculateLineColor()) {
            case BLACK_0:
                edgeButton.setBackground(Colors.get(Color.black));
                edgeButton.setForeground(Colors.get(Color.white));
                break;
            case RED_1:
                mountainButton.setBackground(Colors.get(Color.red));
                mountainButton.setForeground(Colors.get(Color.black));
                break;
            case BLUE_2:
                valleyButton.setBackground(Colors.get(Color.blue));
                valleyButton.setForeground(Colors.get(Color.black));
                break;
            case CYAN_3:
                auxButton.setBackground(Colors.get(Color.cyan));
                auxButton.setForeground(Colors.get(Color.black));
            default:
                break;
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        root.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(-1, 40), null, null, 0, false));
        scrollPane1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 9, new Insets(0, 0, 0, 0), -1, -1));
        scrollPane1.setViewportView(panel1);
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel1.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        cycleGridButton = new JButton();
        cycleGridButton.setActionCommand("changeGridStateAction");
        cycleGridButton.setText("cycleGrid");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 10;
        panel2.add(cycleGridButton, gbc);
        decreaseGridSizeButton = new JButton();
        decreaseGridSizeButton.setActionCommand("gridSizeDecreaseAction");
        decreaseGridSizeButton.setText("decreaseGridSize");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 10;
        panel2.add(decreaseGridSizeButton, gbc);
        gridSizeTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(gridSizeTextField, gbc);
        increaseGridSizeButton = new JButton();
        increaseGridSizeButton.setActionCommand("gridSizeIncreaseAction");
        increaseGridSizeButton.setText("increaseGridSize");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 10;
        panel2.add(increaseGridSizeButton, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel3, new GridConstraints(0, 8, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        resetButton = new JButton();
        resetButton.setActionCommand("resetAction");
        resetButton.setText("reset");
        panel3.add(resetButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(30, -1), null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 7, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel1.add(spacer2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        panel1.add(panel4, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        foldButton = new JButton();
        foldButton.setActionCommand("foldAction");
        foldButton.setText("fold");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 10;
        panel4.add(foldButton, gbc);
        stopFoldingButton = new JButton();
        stopFoldingButton.setActionCommand("haltAction");
        stopFoldingButton.setText("stopFolding");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 10;
        panel4.add(stopFoldingButton, gbc);
        trashButton = new JButton();
        trashButton.setActionCommand("foldedFigureTrashAction");
        trashButton.setText("trash");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 10;
        panel4.add(trashButton, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        panel1.add(panel5, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        mountainButton = new JButton();
        mountainButton.setActionCommand("colRedAction");
        mountainButton.setText("M");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 20;
        panel5.add(mountainButton, gbc);
        valleyButton = new JButton();
        valleyButton.setActionCommand("colBlueAction");
        valleyButton.setText("V");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 20;
        panel5.add(valleyButton, gbc);
        edgeButton = new JButton();
        edgeButton.setActionCommand("colBlackAction");
        edgeButton.setText("E");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 20;
        panel5.add(edgeButton, gbc);
        auxButton = new JButton();
        auxButton.setActionCommand("colCyanAction");
        auxButton.setText("A");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 20;
        panel5.add(auxButton, gbc);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel6, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new GridBagLayout());
        panel6.add(panel7, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        moveButton = new JButton();
        moveButton.setActionCommand("moveCreasePatternAction");
        moveButton.setText("move");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 10;
        panel7.add(moveButton, gbc);
        zoomOutButton = new JButton();
        zoomOutButton.setActionCommand("creasePatternZoomOutAction");
        zoomOutButton.setText("zoomOut");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 10;
        panel7.add(zoomOutButton, gbc);
        zoomTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        panel7.add(zoomTextField, gbc);
        zoomInButton = new JButton();
        zoomInButton.setActionCommand("creasePatternZoomInAction");
        zoomInButton.setText("zoomIn");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 10;
        panel7.add(zoomInButton, gbc);
        final JPanel panel8 = new JPanel();
        panel8.setLayout(new GridBagLayout());
        panel1.add(panel8, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        rotateCounterClockwiseButton = new JButton();
        rotateCounterClockwiseButton.setActionCommand("rotateAnticlockwiseAction");
        rotateCounterClockwiseButton.setText("rotateCounterClockwise");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 10;
        panel8.add(rotateCounterClockwiseButton, gbc);
        rotationTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        panel8.add(rotationTextField, gbc);
        rotateClockwiseButton = new JButton();
        rotateClockwiseButton.setActionCommand("rotateClockwiseAction");
        rotateClockwiseButton.setText("rotateClockwise");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 10;
        panel8.add(rotateClockwiseButton, gbc);
        foldabilityCheckbox = new JCheckBox();
        foldabilityCheckbox.setActionCommand("cAMVAction");
        foldabilityCheckbox.setText("Check Foldability");
        panel1.add(foldabilityCheckbox, new GridConstraints(0, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
