package oriedita.editor.swing.toolsetting;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import oriedita.editor.databinding.CanvasModel;
import oriedita.editor.handler.MouseHandlerSettingGroup;
import oriedita.editor.handler.UiFor;
import oriedita.editor.service.BindingService;
import oriedita.editor.service.ButtonService;
import oriedita.editor.swing.component.combobox.CustomLineTypeComboBoxRenderer;
import origami.crease_pattern.CustomLineTypes;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JPanel;
import java.awt.Insets;

@ApplicationScoped
@UiFor(MouseHandlerSettingGroup.ERASER_COLOR)
public class EraserColorUi implements MouseHandlerUi {
    private final CanvasModel canvasModel;
    private final ButtonService buttonService;
    private JPanel root;
    private JComboBox<CustomLineTypes> colorComboBox;
    private final BindingService bindingService;

    @Inject
    public EraserColorUi(
            CanvasModel canvasModel,
            ButtonService buttonService, BindingService bindingService
    ) {
        this.canvasModel = canvasModel;
        this.buttonService = buttonService;
        this.bindingService = bindingService;
    }

    @Override
    public void init() {
        buttonService.addDefaultListener(root);

        colorComboBox.setModel(new DefaultComboBoxModel<>(CustomLineTypes.values()));
        colorComboBox.setRenderer(new CustomLineTypeComboBoxRenderer());
        bindingService.addBinding(canvasModel, "delLineType", colorComboBox);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        colorComboBox = new JComboBox();
        root.add(colorComboBox, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
