package oriedita.editor.swing.toolsetting;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import oriedita.editor.action.ActionType;
import oriedita.editor.databinding.ApplicationModel;
import oriedita.editor.handler.MouseHandlerSettingGroup;
import oriedita.editor.handler.UiFor;
import oriedita.editor.service.BindingService;
import oriedita.editor.service.ButtonService;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSlider;
import javax.swing.JTextField;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;

@ApplicationScoped
@UiFor(MouseHandlerSettingGroup.FIX_PRECISION_SELECT)
public class FixPrecisionUi implements MouseHandlerUi {
    private JPanel root;
    private JSlider fixPrecisionSlider;
    private JLabel fixPrecisionLabel;
    private JTextField fixPrecisionTextField;

    private final ButtonService buttonService;
    private final ApplicationModel applicationModel;
    private final BindingService bindingService;

    @Inject
    public FixPrecisionUi(ButtonService buttonService,
                          ApplicationModel applicationModel, BindingService bindingService) {
        this.buttonService = buttonService;
        this.applicationModel = applicationModel;
        this.bindingService = bindingService;
    }

    @Override
    public void init() {
        double divisor = 1000.0;
        buttonService.addDefaultListener(root);
        bindingService.addBinding(applicationModel, "fixPrecision", fixPrecisionTextField);
        buttonService.registerTextField(fixPrecisionTextField, ActionType.setFixPrecisionAction.action());
        fixPrecisionTextField.setText(//"0.00" +
                String.valueOf(fixPrecisionSlider.getValue() / divisor));

        fixPrecisionSlider.addChangeListener(l -> {
            applicationModel.setFixPrecision(fixPrecisionSlider.getValue() / (divisor));
            fixPrecisionTextField.setText(String.valueOf(fixPrecisionSlider.getValue() / divisor));
        });
        fixPrecisionTextField.setFocusable(false);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        fixPrecisionSlider = new JSlider();
        fixPrecisionSlider.setMajorTickSpacing(0);
        fixPrecisionSlider.setMaximum(100);
        fixPrecisionSlider.setMinimum(1);
        root.add(fixPrecisionSlider, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fixPrecisionLabel = new JLabel();
        fixPrecisionLabel.setText("Precision");
        root.add(fixPrecisionLabel, new GridConstraints(0, 2, 3, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(58, -1), null, null, 0, false));
        fixPrecisionTextField = new JTextField();
        fixPrecisionTextField.setEditable(false);
        fixPrecisionTextField.setEnabled(true);
        fixPrecisionTextField.setForeground(new Color(-2105377));
        root.add(fixPrecisionTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(40, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
