package oriedita.editor.swing.toolsetting;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import oriedita.editor.action.ActionType;
import oriedita.editor.databinding.ApplicationModel;
import oriedita.editor.handler.MouseHandlerSettingGroup;
import oriedita.editor.handler.UiFor;
import oriedita.editor.service.ButtonService;
import oriedita.editor.swing.component.DraggableTextField;

import javax.swing.JComponent;
import javax.swing.JPanel;
import java.awt.Insets;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;

@ApplicationScoped
@UiFor(MouseHandlerSettingGroup.LINE_DIVISION_COUNT)
public class LineDivisionUi implements MouseHandlerUi {
    private JPanel root;
    private DraggableTextField lineDivisionTextField;
    private final ButtonService buttonService;
    private final ApplicationModel applicationModel;

    @Inject
    public LineDivisionUi(ButtonService buttonService, ApplicationModel applicationModel) {
        this.buttonService = buttonService;
        this.applicationModel = applicationModel;
    }


    @Override
    public void init() {
        buttonService.addDefaultListener(root);
        applicationModel.bind(lineDivisionTextField, "foldLineDividingNumber");
        buttonService.registerTextField(lineDivisionTextField, ActionType.lineSegmentDivisionSetAction.action());
        lineDivisionTextField.setTickDistance(8);
        lineDivisionTextField.addTickListener(i ->
                applicationModel.setFoldLineDividingNumber(applicationModel.getFoldLineDividingNumber() + i));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        lineDivisionTextField = new DraggableTextField();
        root.add(lineDivisionTextField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
