package oriedita.editor.swing.toolsetting;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import oriedita.editor.action.ActionType;
import oriedita.editor.databinding.InternalDivisionRatioModel;
import oriedita.editor.handler.MouseHandlerSettingGroup;
import oriedita.editor.handler.UiFor;
import oriedita.editor.service.ButtonService;
import oriedita.editor.swing.component.DraggableTextField;

import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionListener;

@ApplicationScoped
@UiFor(MouseHandlerSettingGroup.LINE_DIVISION_RATIO)
public class LineDivisonRatioUi implements MouseHandlerUi {
    private JTextField ratio1TextField;
    private JLabel ratioLabel1;
    private JTextField ratio2TextField;
    private JLabel ratioLabel2;
    private JTextField ratio3TextField;
    private JTextField ratio4TextField;
    private JLabel ratioLabel3;
    private JTextField ratio5TextField;
    private JLabel ratioLabel4;
    private JTextField ratio6TextField;
    private JPanel root;

    private final ButtonService buttonService;
    private final InternalDivisionRatioModel internalDivisionRatioModel;

    @Inject
    public LineDivisonRatioUi(ButtonService buttonService,
                              InternalDivisionRatioModel internalDivisionRatioModel) {
        this.buttonService = buttonService;
        this.internalDivisionRatioModel = internalDivisionRatioModel;
    }


    @Override
    public void init() {
        buttonService.addDefaultListener(root);

        internalDivisionRatioModel.bind(ratio1TextField, "internalDivisionRatioA");
        internalDivisionRatioModel.bind(ratio2TextField, "internalDivisionRatioB");
        internalDivisionRatioModel.bind(ratio3TextField, "internalDivisionRatioC");
        internalDivisionRatioModel.bind(ratio4TextField, "internalDivisionRatioD");
        internalDivisionRatioModel.bind(ratio5TextField, "internalDivisionRatioE");
        internalDivisionRatioModel.bind(ratio6TextField, "internalDivisionRatioF");
        buttonService.registerTextField(ratio1TextField, ActionType.lineSegmentInternalDivisionRatioSetAction.action());
        buttonService.registerTextField(ratio2TextField, ActionType.lineSegmentInternalDivisionRatioSetAction.action());
        buttonService.registerTextField(ratio3TextField, ActionType.lineSegmentInternalDivisionRatioSetAction.action());
        buttonService.registerTextField(ratio4TextField, ActionType.lineSegmentInternalDivisionRatioSetAction.action());
        buttonService.registerTextField(ratio5TextField, ActionType.lineSegmentInternalDivisionRatioSetAction.action());
        buttonService.registerTextField(ratio6TextField, ActionType.lineSegmentInternalDivisionRatioSetAction.action());

        buttonService.setIcon(ratioLabel1, "labelPlus");
        buttonService.setIcon(ratioLabel2, "labelSqrt");
        buttonService.setIcon(ratioLabel3, "labelPlus");
        buttonService.setIcon(ratioLabel4, "labelSqrt");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        root.setOpaque(false);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setOpaque(false);
        root.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        ratio1TextField = new JTextField();
        ratio1TextField.setMinimumSize(new Dimension(30, 30));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(ratio1TextField, gbc);
        ratioLabel1 = new JLabel();
        ratioLabel1.setHorizontalAlignment(0);
        ratioLabel1.setText("+");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.ipadx = 5;
        panel1.add(ratioLabel1, gbc);
        ratio2TextField = new JTextField();
        ratio2TextField.setMinimumSize(new Dimension(30, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(ratio2TextField, gbc);
        ratioLabel2 = new JLabel();
        ratioLabel2.setHorizontalAlignment(0);
        ratioLabel2.setText("sqrt");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.ipadx = 5;
        panel1.add(ratioLabel2, gbc);
        ratio3TextField = new JTextField();
        ratio3TextField.setMinimumSize(new Dimension(30, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(ratio3TextField, gbc);
        ratio4TextField = new JTextField();
        ratio4TextField.setMinimumSize(new Dimension(30, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(ratio4TextField, gbc);
        ratioLabel3 = new JLabel();
        ratioLabel3.setHorizontalAlignment(0);
        ratioLabel3.setText("+");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weighty = 1.0;
        gbc.ipadx = 5;
        panel1.add(ratioLabel3, gbc);
        ratio5TextField = new JTextField();
        ratio5TextField.setMinimumSize(new Dimension(30, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(ratio5TextField, gbc);
        ratioLabel4 = new JLabel();
        ratioLabel4.setHorizontalAlignment(0);
        ratioLabel4.setText("sqrt");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.weighty = 1.0;
        gbc.ipadx = 5;
        panel1.add(ratioLabel4, gbc);
        ratio6TextField = new JTextField();
        ratio6TextField.setMinimumSize(new Dimension(30, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(ratio6TextField, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }


}
