package oriedita.editor.swing.toolsetting;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import oriedita.editor.action.ActionType;
import oriedita.editor.databinding.ApplicationModel;
import oriedita.editor.handler.MouseHandlerSettingGroup;
import oriedita.editor.handler.UiFor;
import oriedita.editor.service.ButtonService;
import oriedita.editor.swing.component.DraggableTextField;

import javax.swing.JComponent;
import javax.swing.JPanel;
import java.awt.Insets;

@ApplicationScoped
@UiFor(MouseHandlerSettingGroup.POLYGON_POINT_COUNT)
public class PolygonUi implements MouseHandlerUi {
    private JPanel root;
    private DraggableTextField polygonTextField;

    private final ButtonService buttonService;
    private final ApplicationModel applicationModel;

    @Inject
    public PolygonUi(ButtonService buttonService,
                     ApplicationModel applicationModel) {
        this.buttonService = buttonService;
        this.applicationModel = applicationModel;
    }

    @Override
    public void init() {
        buttonService.addDefaultListener(root);
        applicationModel.bind(polygonTextField, "numPolygonCorners");
        buttonService.registerTextField(polygonTextField, ActionType.polygonSizeSetAction.action());
        polygonTextField.setTickDistance(8);
        polygonTextField.addTickListener(i ->
                applicationModel.setNumPolygonCorners(applicationModel.getNumPolygonCorners() + i));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        polygonTextField = new DraggableTextField();
        root.add(polygonTextField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
