package origami_editor.editor;

import javax.swing.*;
import java.awt.*;

/**
 * BorderLayout for each different part.
 */
public class Editor {
    private final App app;
    private JPanel panel1;
    private Canvas canvas;
    private RightPanel rightPanel;
    private BottomPanel bottomPanel;
    private TopPanel topPanel;
    private LeftPanel leftPanel;

    public Editor(App app) {
        this.app = app;
        $$$setupUI$$$();
    }

    private void createUIComponents() {
        canvas = new Canvas(app);
        rightPanel = new RightPanel(app, app.angleSystemModel);
        bottomPanel = new BottomPanel(app);
        topPanel = new TopPanel(app);
        leftPanel = new LeftPanel(app);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.add(bottomPanel.$$$getRootComponent$$$(), BorderLayout.SOUTH);
        panel1.add(rightPanel.$$$getRootComponent$$$(), BorderLayout.EAST);
        panel1.add(canvas, BorderLayout.CENTER);
        panel1.add(topPanel.$$$getRootComponent$$$(), BorderLayout.NORTH);
        panel1.add(leftPanel.$$$getRootComponent$$$(), BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    public Canvas getCanvas() {
        return canvas;
    }

    public RightPanel getRightPanel() {
        return rightPanel;
    }

    public BottomPanel getBottomPanel() {
        return bottomPanel;
    }

    public TopPanel getTopPanel() {
        return topPanel;
    }

    public LeftPanel getLeftPanel() {
        return leftPanel;
    }
}
