package origami_editor.editor;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.awt.*;

/**
 * BorderLayout for each different part.
 */
@Component
public class Editor {
    private JPanel root;
    private Canvas canvas;
    private RightPanel rightPanel;
    private BottomPanel bottomPanel;
    private TopPanel topPanel;
    private LeftPanel leftPanel;

    public Editor(Canvas canvas, RightPanel rightPanel, BottomPanel bottomPanel, TopPanel topPanel, LeftPanel leftPanel) {
        this.canvas = canvas;
        this.rightPanel = rightPanel;
        this.bottomPanel = bottomPanel;
        this.topPanel = topPanel;
        this.leftPanel = leftPanel;
        $$$setupUI$$$();
    }

    private void createUIComponents() {
     }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        root = new JPanel();
        root.setLayout(new BorderLayout(0, 0));
        root.add(bottomPanel.$$$getRootComponent$$$(), BorderLayout.SOUTH);
        root.add(rightPanel.$$$getRootComponent$$$(), BorderLayout.EAST);
        root.add(canvas, BorderLayout.CENTER);
        root.add(topPanel.$$$getRootComponent$$$(), BorderLayout.NORTH);
        root.add(leftPanel.$$$getRootComponent$$$(), BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

    public Canvas getCanvas() {
        return canvas;
    }
}
