package origami_editor.editor.component;

import origami_editor.editor.App;
import origami_editor.graphic2d.oritacalc.OritaCalc;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FoldedFigureRotate extends JPanel {
    private JButton foldedFigureRotateAntiClockwiseButton;
    private JPanel panel1;
    private JTextField foldedFigureRotateTextField;
    private JButton foldedFigureRotateClockwiseButton;
    private JButton foldedFigureRotateSetButton;

    public FoldedFigureRotate(App app) {
        add($$$getRootComponent$$$());

        foldedFigureRotateAntiClockwiseButton.addActionListener(e -> {
            app.setHelp("qqq/oriagari_p_kaiten.png");

            app.OZ.d_foldedFigure_rotation_correction = OritaCalc.angle_between_m180_180(app.OZ.d_foldedFigure_rotation_correction + 11.25);
            app.OZ.camera_of_foldedFigure.setCameraAngle(app.OZ.d_foldedFigure_rotation_correction);
            app.OZ.camera_of_foldedFigure_front.setCameraAngle(app.OZ.d_foldedFigure_rotation_correction);
            app.OZ.camera_of_foldedFigure_rear.setCameraAngle(app.OZ.d_foldedFigure_rotation_correction);
            app.OZ.camera_of_transparent_front.setCameraAngle(app.OZ.d_foldedFigure_rotation_correction);
            app.OZ.camera_of_transparent_rear.setCameraAngle(app.OZ.d_foldedFigure_rotation_correction);

            foldedFigureRotateTextField.setText(String.valueOf(app.OZ.d_foldedFigure_rotation_correction));
            foldedFigureRotateTextField.setCaretPosition(0);

            app.Button_shared_operation();
            app.canvas.repaint();
        });
        foldedFigureRotateSetButton.addActionListener(e -> {
            double d_foldedFigure_rotation_correction_old = app.OZ.d_foldedFigure_rotation_correction;
            app.OZ.d_foldedFigure_rotation_correction = OritaCalc.angle_between_m180_180(app.String2double(foldedFigureRotateTextField.getText(), d_foldedFigure_rotation_correction_old));

            foldedFigureRotateTextField.setText(String.valueOf(app.OZ.d_foldedFigure_rotation_correction));

            if (app.OZ.d_foldedFigure_rotation_correction != d_foldedFigure_rotation_correction_old) {

                app.OZ.camera_of_foldedFigure.setCameraAngle(app.OZ.d_foldedFigure_rotation_correction);
                app.OZ.camera_of_foldedFigure_front.setCameraAngle(app.OZ.d_foldedFigure_rotation_correction);
                app.OZ.camera_of_foldedFigure_rear.setCameraAngle(app.OZ.d_foldedFigure_rotation_correction);
                app.OZ.camera_of_transparent_front.setCameraAngle(app.OZ.d_foldedFigure_rotation_correction);
                app.OZ.camera_of_transparent_rear.setCameraAngle(app.OZ.d_foldedFigure_rotation_correction);
            }
            foldedFigureRotateTextField.setText(String.valueOf(app.OZ.d_foldedFigure_rotation_correction));
            foldedFigureRotateTextField.setCaretPosition(0);
            app.canvas.repaint();


            app.setHelp("qqq/oriagarizu_kaiten_hosei_set.png");
            app.Button_shared_operation();
            app.canvas.repaint();
        });
        foldedFigureRotateClockwiseButton.addActionListener(e -> {
            app.setHelp("qqq/oriagari_m_kaiten.png");
            app.OZ.d_foldedFigure_rotation_correction = OritaCalc.angle_between_m180_180(app.OZ.d_foldedFigure_rotation_correction - 11.25);
            app.OZ.camera_of_foldedFigure.setCameraAngle(app.OZ.d_foldedFigure_rotation_correction);
            app.OZ.camera_of_foldedFigure_front.setCameraAngle(app.OZ.d_foldedFigure_rotation_correction);
            app.OZ.camera_of_foldedFigure_rear.setCameraAngle(app.OZ.d_foldedFigure_rotation_correction);
            app.OZ.camera_of_transparent_front.setCameraAngle(app.OZ.d_foldedFigure_rotation_correction);
            app.OZ.camera_of_transparent_rear.setCameraAngle(app.OZ.d_foldedFigure_rotation_correction);

            foldedFigureRotateTextField.setText(String.valueOf(app.OZ.d_foldedFigure_rotation_correction));
            foldedFigureRotateTextField.setCaretPosition(0);

            app.Button_shared_operation();
            app.canvas.repaint();
        });
    }

    public JTextField getFoldedFigureRotateTextField() {
        return foldedFigureRotateTextField;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 1, 1));
        panel1.setBackground(new Color(-1));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        foldedFigureRotateAntiClockwiseButton = new JButton();
        foldedFigureRotateAntiClockwiseButton.setIcon(new ImageIcon(getClass().getResource("/ppp/oriagari_p_kaiten.png")));
        panel1.add(foldedFigureRotateAntiClockwiseButton);
        foldedFigureRotateTextField = new JTextField();
        foldedFigureRotateTextField.setColumns(2);
        panel1.add(foldedFigureRotateTextField);
        foldedFigureRotateSetButton = new JButton();
        foldedFigureRotateSetButton.setText("S");
        panel1.add(foldedFigureRotateSetButton);
        foldedFigureRotateClockwiseButton = new JButton();
        foldedFigureRotateClockwiseButton.setIcon(new ImageIcon(getClass().getResource("/ppp/oriagari_m_kaiten.png")));
        panel1.add(foldedFigureRotateClockwiseButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
