package origami_editor.editor.component;

import origami_editor.editor.App;
import origami_editor.editor.databinding.FoldedFigureModel;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class FoldedFigureResize extends JPanel {
    private JButton foldedFigureSizeDecreaseButton;
    private JPanel panel1;
    private JTextField foldedFigureSizeTextField;
    private JButton foldedFigureSizeSetButton;
    private JButton foldedFigureSizeIncreaseButton;

    public FoldedFigureResize(App app) {
        add($$$getRootComponent$$$());

        app.registerButton(foldedFigureSizeSetButton, "foldedFigureSizeSetAction");
        app.registerButton(foldedFigureSizeDecreaseButton, "foldedFigureSizeDecreaseAction");
        app.registerButton(foldedFigureSizeIncreaseButton, "foldedFigureSizeIncreaseAction");

        FoldedFigureModel foldedFigureModel = app.foldedFigureModel;
        foldedFigureSizeSetButton.addActionListener(e -> foldedFigureModel.setScale(app.string2double(foldedFigureSizeTextField.getText(), foldedFigureModel.getScale())));
        foldedFigureSizeDecreaseButton.addActionListener(e -> foldedFigureModel.zoomOut());
        foldedFigureSizeIncreaseButton.addActionListener(e -> foldedFigureModel.zoomIn());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        foldedFigureSizeDecreaseButton = new JButton();
        foldedFigureSizeDecreaseButton.setIcon(new ImageIcon(getClass().getResource("/ppp/oriagari_syukusyou.png")));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(foldedFigureSizeDecreaseButton, gbc);
        foldedFigureSizeTextField = new JTextField();
        foldedFigureSizeTextField.setColumns(2);
        foldedFigureSizeTextField.setHorizontalAlignment(4);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(foldedFigureSizeTextField, gbc);
        foldedFigureSizeSetButton = new JButton();
        foldedFigureSizeSetButton.setText("S");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(foldedFigureSizeSetButton, gbc);
        foldedFigureSizeIncreaseButton = new JButton();
        foldedFigureSizeIncreaseButton.setIcon(new ImageIcon(getClass().getResource("/ppp/oriagari_kakudai.png")));
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(foldedFigureSizeIncreaseButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    public String getText() {
        return foldedFigureSizeTextField.getText();
    }

    public void setText(String text) {
        foldedFigureSizeTextField.setText(text);
        foldedFigureSizeTextField.setCaretPosition(0);
    }
}
