package origami_editor.editor.component;

import origami_editor.editor.App;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class FoldedFigureResize extends JPanel {
    private JButton foldedFigureSizeDecreaseButton;
    private JPanel panel1;
    private JTextField foldedFigureSizeTextField;
    private JButton foldedFigureSizeSetButton;
    private JButton foldedFigureSizeIncreaseButton;

    public FoldedFigureResize(App app) {
        add($$$getRootComponent$$$());

        foldedFigureSizeSetButton.addActionListener(e -> {
            app.foldedFigureConfiguration.setScale(app.String2double(foldedFigureSizeTextField.getText(), app.foldedFigureConfiguration.getScale()));

            app.setHelp("oriagarizu_syukusyaku_keisuu_set");
            app.Button_shared_operation();
            app.updateFoldedFigure();
        });
        double root2 = Math.sqrt(Math.sqrt(Math.sqrt(2.0)));
        foldedFigureSizeDecreaseButton.addActionListener(e -> {
            app.setHelp("oriagari_syukusyou");

            app.foldedFigureConfiguration.setScale(app.foldedFigureConfiguration.getScale() / root2);

            app.Button_shared_operation();
            app.updateFoldedFigure();
        });
        foldedFigureSizeIncreaseButton.addActionListener(e -> {
            app.setHelp("oriagari_kakudai");

            app.foldedFigureConfiguration.setScale(app.foldedFigureConfiguration.getScale() * root2);

            app.Button_shared_operation();
            app.updateFoldedFigure();
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setBackground(new Color(-1));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        foldedFigureSizeDecreaseButton = new JButton();
        foldedFigureSizeDecreaseButton.setIcon(new ImageIcon(getClass().getResource("/ppp/oriagari_syukusyou.png")));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(foldedFigureSizeDecreaseButton, gbc);
        foldedFigureSizeTextField = new JTextField();
        foldedFigureSizeTextField.setColumns(2);
        foldedFigureSizeTextField.setHorizontalAlignment(4);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(foldedFigureSizeTextField, gbc);
        foldedFigureSizeSetButton = new JButton();
        foldedFigureSizeSetButton.setText("S");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(foldedFigureSizeSetButton, gbc);
        foldedFigureSizeIncreaseButton = new JButton();
        foldedFigureSizeIncreaseButton.setIcon(new ImageIcon(getClass().getResource("/ppp/oriagari_kakudai.png")));
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(foldedFigureSizeIncreaseButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    public String getText() {
        return foldedFigureSizeTextField.getText();
    }

    public void setText(String text) {
        foldedFigureSizeTextField.setText(text);
        foldedFigureSizeTextField.setCaretPosition(0);
    }
}
