package origami_editor.editor.component;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

import java.util.ArrayList;
import java.util.List;

public class UndoRedo extends JPanel {
    private JButton undoButton;
    private JPanel panel1;
    private JTextField undoCountTextField;
    private JButton setUndoCountButton;
    private JButton redoButton;

    public UndoRedo() {
    }

    public void addUndoActionListener(ActionListener listener) {
        undoButton.addActionListener(listener);
    }

    public void addRedoActionListener(ActionListener listener) {
        redoButton.addActionListener(listener);
    }

    public void addSetUndoCountActionListener(ActionListener listener) {
        setUndoCountButton.addActionListener(listener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.setEnabled(true);
        undoButton = new JButton();
        undoButton.setIcon(new ImageIcon(getClass().getResource("/ppp/undo.png")));
        panel1.add(undoButton);
        undoCountTextField = new JTextField();
        undoCountTextField.setColumns(2);
        undoCountTextField.setMinimumSize(new Dimension(60, 30));
        panel1.add(undoCountTextField);
        setUndoCountButton = new JButton();
        setUndoCountButton.setText("S");
        panel1.add(setUndoCountButton);
        redoButton = new JButton();
        redoButton.setIcon(new ImageIcon(getClass().getResource("/ppp/redo.png")));
        panel1.add(redoButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private void createUIComponents() {
        panel1 = this;
    }

    public void setText(String s) {
        undoCountTextField.setText(s);
    }

    public String getText() {
        return undoCountTextField.getText();
    }
}
