package oriedita.editor.swing.dialog;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import java.awt.Frame;
import java.awt.Insets;
import java.awt.event.KeyEvent;

public class SaveTypeDialog extends JDialog {
    private JPanel contentPane;
    private JButton creasePatternCpSavesButton;
    private JButton completeOriAlsoSavesButton;
    private JButton completeFoldAlsoSavesButton;

    private String saveType = null;

    public SaveTypeDialog(Frame owner) {
        super(owner, "Save type", ModalityType.APPLICATION_MODAL);
        setContentPane(contentPane);

        creasePatternCpSavesButton.addActionListener(e -> {
            saveType = ".cp";
            dispose();
        });
        completeOriAlsoSavesButton.addActionListener(e -> {
            saveType = ".ori";
            dispose();
        });
        completeFoldAlsoSavesButton.addActionListener(e -> {
            saveType = ".fold";
            dispose();
        });

        // call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(
                e -> dispose(),
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
        );

        pack();

        setLocationRelativeTo(owner);
    }

    public static String showSaveTypeDialog(Frame owner) {
        SaveTypeDialog saveTypeDialog = new SaveTypeDialog(owner);
        saveTypeDialog.setVisible(true);

        String saveType = saveTypeDialog.saveType;

        saveTypeDialog.dispose();

        return saveType;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        creasePatternCpSavesButton = new JButton();
        creasePatternCpSavesButton.setHorizontalAlignment(0);
        creasePatternCpSavesButton.setText("<html><br/><b>.CP</b><br/><br/> Save only M/V/A/E lines.<br/><br/><i>Robust and compatible file<br/>format that is widely used to<br/>share crease patterns.</i><br/><br/><html/>");
        creasePatternCpSavesButton.setVerticalAlignment(1);
        panel1.add(creasePatternCpSavesButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        completeOriAlsoSavesButton = new JButton();
        completeOriAlsoSavesButton.setHorizontalAlignment(0);
        completeOriAlsoSavesButton.setText("<html><br/><b>.ORI</b><br/><br/>Save all lines, circles, text,<br/>and grid.<br/> <br/> <i>Oriedita exclusive file format.</i><br/>");
        completeOriAlsoSavesButton.setVerticalAlignment(1);
        panel1.add(completeOriAlsoSavesButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        completeFoldAlsoSavesButton = new JButton();
        completeFoldAlsoSavesButton.setText("<html><br/><b>.FOLD</b><br/><br/>Save all lines, circles, and text.<br/> <br/> <i>Compatible with other origami<br/>related software. </i><br/>");
        completeFoldAlsoSavesButton.setVerticalAlignment(1);
        panel1.add(completeFoldAlsoSavesButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
